---
title: "Figure_12_LiDAR_vs_SfM_Profile"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
# Load packages
pacman::p_load(terra, sf, tidyverse, ggpubr)

# Load functions
source("./src/r/functions.r")

# Load transects for elevation profiles
transects <- read_sf("./data/shp/Elevation_Profiles.shp")
```

```{r}
paths <- c("./data/dems/sfm/20210316_Deep_RGB_2cm_DEM_clipped.tif",
    "./data/dems/lidar/20210316_Deep_LiDAR_DEM_clipped.tif")

lidar_sfm_1 <- create_elevation_profile(paths, "noveg_1")

lidar_sfm_1 <- lidar_sfm_1 +
  labs(title = "Transect 1") +
  theme(legend.direction = "vertical",
        legend.position = c(0.15, 0.10),
        legend.text = element_text(size = 8),
        legend.key.width = unit(0.5, "cm"),
        legend.key.height = unit(0.1, "cm"),
        legend.spacing.y = unit(0.1, "cm"),
        legend.background = element_rect(fill = "transparent"),
        legend.margin = margin(0.1, 0.1, 0.1, 0.1, unit = "cm"),
        axis.text = element_text(size = 8),
        axis.title = element_text(size = 8, face = "bold"),
        plot.title = element_text(size = 10, face = "bold", hjust = -0.073)
        ) +
  scale_y_continuous(limits = c(0, 1.5), breaks = seq(0, 1.5, 0.5)) +
  scale_colour_manual(values = RColorBrewer::brewer.pal(8, "Set2")[c(3,5)], labels = c('SfM', 'LiDAR'))


lidar_sfm_2 <- create_elevation_profile(paths, "noveg_3")

lidar_sfm_2 <- lidar_sfm_2 +
  labs(title = "Transect 2") +
  theme(legend.direction = "vertical",
        legend.position = c(0.15, 0.10),
        legend.text = element_text(size = 8),
        legend.key.width = unit(0.5, "cm"),
        legend.key.height = unit(0.1, "cm"),
        legend.spacing.y = unit(0.1, "cm"),
        legend.background = element_rect(fill = "transparent"),
        legend.margin = margin(0.1, 0.1, 0.1, 0.1, unit = "cm"),
        axis.text = element_text(size = 8),
        axis.title = element_text(size = 8, face = "bold"),
        plot.title = element_text(size = 10, face = "bold", hjust = -0.073)
        ) +
  scale_y_continuous(limits = c(0, 2.5), breaks = seq(0, 2.5, 0.5)) +
  scale_colour_manual(values = RColorBrewer::brewer.pal(8, "Set2")[c(3,5)], labels = c('SfM', 'LiDAR'))

# ragg::agg_png("16x8.png", width = 16, height = 8, units = "cm", res = 600)

ggpubr::ggarrange(
  lidar_sfm_1,
  lidar_sfm_2 + 
    rremove("y.title"),
  nrow = 1
  )
```


```{r}
ggsave("./figures/figure_10_lidar_sfm.png",
     width = 16,
     height = 8,
     units = "cm")

```
