---
title: "Process boolcoomatta rainfall"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
rain <- read_csv("./data/rainfall/boolcoomatta_guage.csv")
rain <- rain %>% 
  pivot_longer(cols = 3:ncol(.), names_to = "month", values_to = "rainfall")

# Change months to numbers
rain <- rain %>%
  mutate(month = recode(month,
    Jan = 1,
    Feb = 2,
    Mar = 3,
    Apr = 4,
    May = 5,
    Jun = 6,
    Jul = 7,
    Aug = 8,
    Sep = 9,
    Oct = 10,
    Nov = 11,
    Dec = 12
  ))

rain <- rain %>% 
  mutate(date = paste(year, month, day, sep = "-"), .before = 1)

rain$date <- as_date(rain$date)

rain <- rain %>% 
  filter(!is.na(date)) %>% 
  select(-c("year", "day", "month"))

# Set NA rainfalls to zero
rain$rainfall[which(is.na(rain$rainfall))] <- 0
```

# Produce plot

```{r}
rain %>%
  filter(date > as_date("2021-03-16")) %>% 
  filter(date < as_date("2022-03-01")) %>% 
  ggplot(aes(x = date, y = rainfall)) +
  geom_col(fill = "blue") +
  geom_rect(aes(xmin = as_date("2021-03-16"),
                xmax = as_date("2021-03-18"),
                ymin = 0,
                ymax = Inf),
            fill = "green") +  
  geom_rect(aes(xmin = as_date("2021-05-05"),
                xmax = as_date("2021-05-06"),
                ymin = 0,
                ymax = Inf),
            fill = "green") +  
  geom_col(aes(x = as_date("2022-03-01"),
                y = Inf),
            fill = "green") +
  theme_minimal() +
  theme(strip.background = element_blank(),
        strip.text = element_text(colour = NA),
        axis.text.y = element_text(size = 25, margin = margin(r = 10)),
        axis.text.x = element_text(size = 25, margin = margin(t = 10)),
        axis.title.x = element_text(size = 25, margin = margin(t = 20)),
        axis.title.y = element_text(size = 25, margin = margin(r = 20)),
        legend.key.height = unit(0.5, "cm"),
        legend.key.width = unit(1, "cm"),
        legend.position = c(0.7, 0.04),
        legend.direction = "horizontal",
        legend.background = element_rect(fill = "transparent"),
        legend.text = element_text(size = 25),
        legend.title = element_text(size = 25, face = "bold"),
        plot.margin = unit(c(t = 10, r = 0, l = 0, r = 0), "mm")) + 
  labs(y = "Rainfall (mm)",
       x = "Date") +
  scale_y_continuous(breaks = seq(0, max(rain$rainfall) + 5, by = 5), minor_breaks = NULL) +
  scale_x_date(date_breaks = "3 month", date_labels = "%b")

```

